export interface Problem {
  id: string;
  title: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  leetcodeUrl: string;
  acceptance: string;
  frequency: string;
}

export const problemsList: Problem[] = [
  { id: '1', title: 'Two Sum', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/two-sum', acceptance: '56.6%', frequency: '75.0%' },
  { id: '3', title: 'Longest Substring Without Repeating Characters', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/longest-substring-without-repeating-characters', acceptance: '37.9%', frequency: '62.5%' },
  { id: '4', title: 'Median of Two Sorted Arrays', difficulty: 'Hard', leetcodeUrl: 'https://leetcode.com/problems/median-of-two-sorted-arrays', acceptance: '45.2%', frequency: '37.5%' },
  { id: '6', title: 'Zigzag Conversion', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/zigzag-conversion', acceptance: '52.9%', frequency: '100.0%' },
  { id: '11', title: 'Container With Most Water', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/container-with-most-water', acceptance: '59.0%', frequency: '50.0%' },
  { id: '15', title: '3Sum', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/3sum', acceptance: '38.0%', frequency: '37.5%' },
  { id: '20', title: 'Valid Parentheses', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/valid-parentheses', acceptance: '43.2%', frequency: '37.5%' },
  { id: '33', title: 'Search in Rotated Sorted Array', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/search-in-rotated-sorted-array', acceptance: '43.7%', frequency: '50.0%' },
  { id: '34', title: 'Find First and Last Position of Element in Sorted Array', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array', acceptance: '47.8%', frequency: '50.0%' },
  { id: '38', title: 'Count and Say', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/count-and-say', acceptance: '61.7%', frequency: '37.5%' },
  { id: '42', title: 'Trapping Rain Water', difficulty: 'Hard', leetcodeUrl: 'https://leetcode.com/problems/trapping-rain-water', acceptance: '66.2%', frequency: '50.0%' },
  { id: '49', title: 'Group Anagrams', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/group-anagrams', acceptance: '71.7%', frequency: '75.0%' },
  { id: '1969', title: 'Minimum Non-Zero Product of the Array Elements', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/minimum-non-zero-product-of-the-array-elements', acceptance: '36.8%', frequency: '75.0%' },
  { id: '56', title: 'Merge Intervals', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/merge-intervals', acceptance: '50.5%', frequency: '62.5%' },
  { id: '75', title: 'Sort Colors', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/sort-colors', acceptance: '68.6%', frequency: '50.0%' },
  { id: '79', title: 'Word Search', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/word-search', acceptance: '46.3%', frequency: '75.0%' },
  { id: '88', title: 'Merge Sorted Array', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/merge-sorted-array', acceptance: '53.9%', frequency: '50.0%' },
  { id: '1999', title: 'Smallest Greater Multiple Made of Two Digits', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/smallest-greater-multiple-made-of-two-digits', acceptance: '48.2%', frequency: '75.0%' },
  { id: '2056', title: 'Number of Valid Move Combinations On Chessboard', difficulty: 'Hard', leetcodeUrl: 'https://leetcode.com/problems/number-of-valid-move-combinations-on-chessboard', acceptance: '48.4%', frequency: '75.0%' },
  { id: '121', title: 'Best Time to Buy and Sell Stock', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock', acceptance: '56.0%', frequency: '62.5%' },
  { id: '2062', title: 'Count Vowel Substrings of a String', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/count-vowel-substrings-of-a-string', acceptance: '72.4%', frequency: '62.5%' },
  { id: '146', title: 'LRU Cache', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/lru-cache', acceptance: '46.3%', frequency: '75.0%' },
  { id: '152', title: 'Maximum Product Subarray', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/maximum-product-subarray', acceptance: '35.6%', frequency: '37.5%' },
  { id: '200', title: 'Number of Islands', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/number-of-islands', acceptance: '63.3%', frequency: '75.0%' },
  { id: '206', title: 'Reverse Linked List', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/reverse-linked-list', acceptance: '79.9%', frequency: '37.5%' },
  { id: '212', title: 'Word Search II', difficulty: 'Hard', leetcodeUrl: 'https://leetcode.com/problems/word-search-ii', acceptance: '37.8%', frequency: '37.5%' },
  { id: '237', title: 'Delete Node in a Linked List', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/delete-node-in-a-linked-list', acceptance: '83.2%', frequency: '37.5%' },
  { id: '238', title: 'Product of Array Except Self', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/product-of-array-except-self', acceptance: '68.3%', frequency: '75.0%' },
  { id: '242', title: 'Valid Anagram', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/valid-anagram', acceptance: '67.4%', frequency: '37.5%' },
  { id: '2183', title: 'Count Array Pairs Divisible by K', difficulty: 'Hard', leetcodeUrl: 'https://leetcode.com/problems/count-array-pairs-divisible-by-k', acceptance: '30.4%', frequency: '75.0%' },
  { id: '300', title: 'Longest Increasing Subsequence', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/longest-increasing-subsequence', acceptance: '58.7%', frequency: '75.0%' },
  { id: '347', title: 'Top K Frequent Elements', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/top-k-frequent-elements', acceptance: '65.2%', frequency: '50.0%' },
  { id: '2366', title: 'Minimum Replacements to Sort the Array', difficulty: 'Hard', leetcodeUrl: 'https://leetcode.com/problems/minimum-replacements-to-sort-the-array', acceptance: '53.2%', frequency: '50.0%' },
  { id: '2380', title: 'Time Needed to Rearrange a Binary String', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/time-needed-to-rearrange-a-binary-string', acceptance: '52.1%', frequency: '75.0%' },
  { id: '2402', title: 'Meeting Rooms III', difficulty: 'Hard', leetcodeUrl: 'https://leetcode.com/problems/meeting-rooms-iii', acceptance: '48.9%', frequency: '50.0%' },
  { id: '560', title: 'Subarray Sum Equals K', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/subarray-sum-equals-k', acceptance: '46.3%', frequency: '50.0%' },
  { id: '2554', title: 'Maximum Number of Integers to Choose From a Range I', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/maximum-number-of-integers-to-choose-from-a-range-i', acceptance: '67.9%', frequency: '75.0%' },
  { id: '2586', title: 'Count the Number of Vowel Strings in Range', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/count-the-number-of-vowel-strings-in-range', acceptance: '73.9%', frequency: '75.0%' },
  { id: '2524', title: 'Maximum Frequency Score of a Subarray', difficulty: 'Hard', leetcodeUrl: 'https://leetcode.com/problems/maximum-frequency-score-of-a-subarray', acceptance: '35.7%', frequency: '75.0%' },
  { id: '2559', title: 'Count Vowel Strings in Ranges', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/count-vowel-strings-in-ranges', acceptance: '67.8%', frequency: '75.0%' },
  { id: '2557', title: 'Maximum Number of Integers to Choose From a Range II', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/maximum-number-of-integers-to-choose-from-a-range-ii', acceptance: '35.0%', frequency: '75.0%' },
  { id: '713', title: 'Subarray Product Less Than K', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/subarray-product-less-than-k', acceptance: '53.5%', frequency: '50.0%' },
  { id: '767', title: 'Reorganize String', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/reorganize-string', acceptance: '56.6%', frequency: '50.0%' },
  { id: '851', title: 'Loud and Rich', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/loud-and-rich', acceptance: '62.7%', frequency: '62.5%' },
  { id: '895', title: 'Maximum Frequency Stack', difficulty: 'Hard', leetcodeUrl: 'https://leetcode.com/problems/maximum-frequency-stack', acceptance: '66.5%', frequency: '37.5%' },
  { id: '1010', title: 'Pairs of Songs With Total Durations Divisible by 60', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/pairs-of-songs-with-total-durations-divisible-by-60', acceptance: '53.4%', frequency: '62.5%' },
  { id: '1229', title: 'Meeting Scheduler', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/meeting-scheduler', acceptance: '55.2%', frequency: '75.0%' },
  { id: '1200', title: 'Minimum Absolute Difference', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/minimum-absolute-difference', acceptance: '71.0%', frequency: '75.0%' },
  { id: '1473', title: 'Paint House III', difficulty: 'Hard', leetcodeUrl: 'https://leetcode.com/problems/paint-house-iii', acceptance: '61.1%', frequency: '75.0%' },
  { id: '1589', title: 'Maximum Sum Obtained of Any Permutation', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/maximum-sum-obtained-of-any-permutation', acceptance: '39.9%', frequency: '75.0%' },
  { id: '1283', title: 'Find the Smallest Divisor Given a Threshold', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold', acceptance: '64.9%', frequency: '62.5%' },
  { id: '198', title: 'House Robber', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/house-robber', acceptance: '52.7%', frequency: '50.0%' },
  { id: '68', title: 'Text Justification', difficulty: 'Hard', leetcodeUrl: 'https://leetcode.com/problems/text-justification', acceptance: '49.7%', frequency: '50.0%' },
  { id: '349', title: 'Intersection of Two Arrays', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/intersection-of-two-arrays', acceptance: '77.1%', frequency: '37.5%' },
  { id: '355', title: 'Design Twitter', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/design-twitter', acceptance: '43.7%', frequency: '37.5%' },
  { id: '48', title: 'Rotate Image', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/rotate-image', acceptance: '78.9%', frequency: '50.0%' },
  { id: '215', title: 'Kth Largest Element in an Array', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/kth-largest-element-in-an-array', acceptance: '68.6%', frequency: '50.0%' },
  { id: '1671', title: 'Minimum Number of Removals to Make Mountain Array', difficulty: 'Hard', leetcodeUrl: 'https://leetcode.com/problems/minimum-number-of-removals-to-make-mountain-array', acceptance: '54.8%', frequency: '37.5%' },
  { id: '1963', title: 'Minimum Number of Swaps to Make the String Balanced', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/minimum-number-of-swaps-to-make-the-string-balanced', acceptance: '78.1%', frequency: '50.0%' },
  { id: '53', title: 'Maximum Subarray', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/maximum-subarray', acceptance: '52.7%', frequency: '62.5%' },
  { id: '945', title: 'Minimum Increment to Make Array Unique', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/minimum-increment-to-make-array-unique', acceptance: '60.5%', frequency: '50.0%' },
  { id: '2491', title: 'Divide Players Into Teams of Equal Skill', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/divide-players-into-teams-of-equal-skill', acceptance: '68.9%', frequency: '37.5%' },
  { id: '1358', title: 'Number of Substrings Containing All Three Characters', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/number-of-substrings-containing-all-three-characters', acceptance: '73.4%', frequency: '37.5%' },
  { id: '528', title: 'Random Pick with Weight', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/random-pick-with-weight', acceptance: '48.7%', frequency: '50.0%' },
  { id: '322', title: 'Coin Change', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/coin-change', acceptance: '47.5%', frequency: '75.0%' },
  { id: '41', title: 'First Missing Positive', difficulty: 'Hard', leetcodeUrl: 'https://leetcode.com/problems/first-missing-positive', acceptance: '41.9%', frequency: '37.5%' },
  { id: '1669', title: 'Merge In Between Linked Lists', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/merge-in-between-linked-lists', acceptance: '82.7%', frequency: '37.5%' },
  { id: '162', title: 'Find Peak Element', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/find-peak-element', acceptance: '46.7%', frequency: '50.0%' },
  { id: '2697', title: 'Lexicographically Smallest Palindrome', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/lexicographically-smallest-palindrome', acceptance: '80.5%', frequency: '37.5%' },
  { id: '697', title: 'Degree of an Array', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/degree-of-an-array', acceptance: '57.9%', frequency: '50.0%' },
  { id: '2625', title: 'Flatten Deeply Nested Array', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/flatten-deeply-nested-array', acceptance: '65.1%', frequency: '37.5%' },
  { id: '55', title: 'Jump Game', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/jump-game', acceptance: '40.1%', frequency: '37.5%' },
  { id: '295', title: 'Find Median from Data Stream', difficulty: 'Hard', leetcodeUrl: 'https://leetcode.com/problems/find-median-from-data-stream', acceptance: '53.9%', frequency: '37.5%' },
  { id: '54', title: 'Spiral Matrix', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/spiral-matrix', acceptance: '55.4%', frequency: '37.5%' },
  { id: '221', title: 'Maximal Square', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/maximal-square', acceptance: '49.6%', frequency: '75.0%' },
  { id: '1353', title: 'Maximum Number of Events That Can Be Attended', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/maximum-number-of-events-that-can-be-attended', acceptance: '38.8%', frequency: '62.5%' },
  { id: '1046', title: 'Last Stone Weight', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/last-stone-weight', acceptance: '66.2%', frequency: '62.5%' },
  { id: '875', title: 'Koko Eating Bananas', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/koko-eating-bananas', acceptance: '49.4%', frequency: '50.0%' },
  { id: '647', title: 'Palindromic Substrings', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/palindromic-substrings', acceptance: '72.3%', frequency: '50.0%' },
  { id: '128', title: 'Longest Consecutive Sequence', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/longest-consecutive-sequence', acceptance: '47.0%', frequency: '50.0%' },
  { id: '460', title: 'LFU Cache', difficulty: 'Hard', leetcodeUrl: 'https://leetcode.com/problems/lfu-cache', acceptance: '47.9%', frequency: '37.5%' },
  { id: '36', title: 'Valid Sudoku', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/valid-sudoku', acceptance: '63.7%', frequency: '50.0%' },
  { id: '202', title: 'Happy Number', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/happy-number', acceptance: '58.8%', frequency: '50.0%' },
  { id: '207', title: 'Course Schedule', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/course-schedule', acceptance: '50.3%', frequency: '37.5%' },
  { id: '240', title: 'Search a 2D Matrix II', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/search-a-2d-matrix-ii', acceptance: '56.3%', frequency: '37.5%' },
  { id: '1235', title: 'Maximum Profit in Job Scheduling', difficulty: 'Hard', leetcodeUrl: 'https://leetcode.com/problems/maximum-profit-in-job-scheduling', acceptance: '54.5%', frequency: '37.5%' },
  { id: '259', title: '3Sum Smaller', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/3sum-smaller', acceptance: '51.2%', frequency: '50.0%' },
  { id: '124', title: 'Binary Tree Maximum Path Sum', difficulty: 'Hard', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-maximum-path-sum', acceptance: '41.8%', frequency: '37.5%' },
  { id: '735', title: 'Asteroid Collision', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/asteroid-collision', acceptance: '46.4%', frequency: '50.0%' },
  { id: '1160', title: 'Find Words That Can Be Formed by Characters', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/find-words-that-can-be-formed-by-characters', acceptance: '71.3%', frequency: '75.0%' },
  { id: '2385', title: 'Amount of Time for Binary Tree to Be Infected', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/amount-of-time-for-binary-tree-to-be-infected', acceptance: '64.8%', frequency: '37.5%' },
  { id: '283', title: 'Move Zeroes', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/move-zeroes', acceptance: '63.2%', frequency: '37.5%' },
  { id: '780', title: 'Reaching Points', difficulty: 'Hard', leetcodeUrl: 'https://leetcode.com/problems/reaching-points', acceptance: '34.0%', frequency: '50.0%' },
  { id: '994', title: 'Rotting Oranges', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/rotting-oranges', acceptance: '57.6%', frequency: '37.5%' },
  { id: '78', title: 'Subsets', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/subsets', acceptance: '81.7%', frequency: '50.0%' },
  { id: '24', title: 'Swap Nodes in Pairs', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/swap-nodes-in-pairs', acceptance: '68.3%', frequency: '37.5%' },
  { id: '1202', title: 'Smallest String With Swaps', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/smallest-string-with-swaps', acceptance: '60.1%', frequency: '50.0%' },
  { id: '402', title: 'Remove K Digits', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/remove-k-digits', acceptance: '35.9%', frequency: '37.5%' },
  { id: '1268', title: 'Search Suggestions System', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/search-suggestions-system', acceptance: '65.1%', frequency: '37.5%' },
  { id: '1839', title: 'Longest Substring Of All Vowels in Order', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/longest-substring-of-all-vowels-in-order', acceptance: '51.2%', frequency: '37.5%' },
  { id: '297', title: 'Serialize and Deserialize Binary Tree', difficulty: 'Hard', leetcodeUrl: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree', acceptance: '59.9%', frequency: '37.5%' },
  { id: '70', title: 'Climbing Stairs', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/climbing-stairs', acceptance: '53.8%', frequency: '37.5%' },
  { id: '1060', title: 'Missing Element in Sorted Array', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/missing-element-in-sorted-array', acceptance: '59.6%', frequency: '37.5%' },
  { id: '412', title: 'Fizz Buzz', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/fizz-buzz', acceptance: '74.9%', frequency: '37.5%' },
  { id: '169', title: 'Majority Element', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/majority-element', acceptance: '66.0%', frequency: '37.5%' },
  { id: '73', title: 'Set Matrix Zeroes', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/set-matrix-zeroes', acceptance: '61.9%', frequency: '37.5%' },
  { id: '1209', title: 'Remove All Adjacent Duplicates in String II', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string-ii', acceptance: '60.5%', frequency: '37.5%' },
  { id: '692', title: 'Top K Frequent Words', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/top-k-frequent-words', acceptance: '59.8%', frequency: '50.0%' },
  { id: '1926', title: 'Nearest Exit from Entrance in Maze', difficulty: 'Medium', leetcodeUrl: 'https://leetcode.com/problems/nearest-exit-from-entrance-in-maze', acceptance: '48.0%', frequency: '37.5%' },
  { id: '1251', title: 'Average Selling Price', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/average-selling-price', acceptance: '37.0%', frequency: '37.5%' },
  { id: '1854', title: 'Maximum Population Year', difficulty: 'Easy', leetcodeUrl: 'https://leetcode.com/problems/maximum-population-year', acceptance: '63.2%', frequency: '37.5%' },
];
